# Generated by Django 4.0.3 on 2022-11-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counting',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='counting',
            name='link',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='counting',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='counting',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
