# Generated by Django 4.0.3 on 2022-11-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_counting_body_counting_category_counting_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counting',
            name='body',
        ),
        migrations.RemoveField(
            model_name='counting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='counting',
            name='link',
        ),
        migrations.RemoveField(
            model_name='counting',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='counting',
            name='title',
        ),
    ]
