# Generated by Django 4.0.3 on 2022-11-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_delete_detail_project_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='show',
        ),
    ]
